version: '3'

services:
  api:
    build:
        context: .
        dockerfile: TransferenciaNFC/Dockerfile
    ports:
        - 5001:80
    depends_on:
        - db-server
        
  db-server:
    container_name: db-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=transferencia
    ports:
      - "1433:1433"